development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url:  postgres://yhodzxzjcevelm:3faa941e3a68713edaee71d3e4229273d4e40a8870a6f86620b81aae6e422d20@ec2-174-129-224-33.compute-1.amazonaws.com:5432/d9llpnin05fag2
